import {
  ADMIN_FIELD_LABELS_UI,
  ADMIN_RENDER_UI_TEXT,
  ADMIN_UI_TEXT,
  ADMIN_VALIDATION_UI_TEXT,
} from "../../shared/constants/ui-text.ar.js";
import { createStateStore } from "../../shared/state/create-state-store.js";
import { renderIcon } from "../../shared/ui/visual/icons.js";

function byId(id) {
  return document.getElementById(id);
}

function getElements() {
  const productEditorShell = byId("productEditorShell");
  const categoryEditorShell = byId("categoryEditorShell");

  return {
    authSection: byId("authSection"),
    dashboardSection: byId("dashboardSection"),
    adminPreviewGate: byId("adminPreviewGate"),
    adminPreviewGateTitle: byId("adminPreviewGateTitle"),
    adminPreviewGateText: byId("adminPreviewGateText"),
    authGateMessage: byId("authGateMessage"),
    authGateFeedback: byId("authGateFeedback"),
    btnGoToAuth: byId("btnGoToAuth"),
    btnRetryAdmin: byId("btnRetryAdmin"),
    btnAuthLogout: byId("btnAuthLogout"),
    btnLogout: byId("btnLogout"),
    btnOrdersInbox: byId("btnOrdersInbox"),
    btnOpenSite: byId("btnOpenSite"),
    newOrdersBadge: byId("newOrdersBadge"),
    productForm: byId("productForm"),
    prodIdInput: byId("prodId"),
    prodName: byId("prodName"),
    prodPrice: byId("prodPrice"),
    prodCategory: byId("prodCategory"),
    prodImage: byId("prodImage"),
    prodImageName: byId("prodImageName"),
    currentImgUrl: byId("currentImgUrl"),
    productCategoryHint: byId("productCategoryHint"),
    btnSaveProduct: byId("btnSaveProduct"),
    btnCancelEdit: byId("btnCancelEdit"),
    btnOpenProductEditor: byId("btnOpenProductEditor"),
    btnCloseProductEditor: byId("btnCloseProductEditor"),
    productEditorShell,
    productEditorSurface: productEditorShell?.querySelector(".product-editor-surface"),
    productEditorTitle: byId("productEditorTitle"),
    productEditorSubtitle: byId("productEditorSubtitle"),
    categoryForm: byId("categoryForm"),
    catIdInput: byId("catId"),
    catNameInput: byId("catName"),
    catIconInput: byId("catIcon"),
    catOrderInput: byId("catOrder"),
    btnSaveCategory: byId("btnSaveCategory"),
    btnCancelCategoryEdit: byId("btnCancelCategoryEdit"),
    btnOpenCategoryEditor: byId("btnOpenCategoryEditor"),
    btnCloseCategoryEditor: byId("btnCloseCategoryEditor"),
    categoryEditorShell,
    categoryEditorSurface: categoryEditorShell?.querySelector(".category-editor-surface"),
    categoryEditorTitle: byId("categoryEditorTitle"),
    categoryEditorSubtitle: byId("categoryEditorSubtitle"),
    settingsForm: byId("settingsForm"),
    heroImageUrlInput: byId("heroImageUrl"),
    heroImageFileInput: byId("heroImageFile"),
    heroImageFileName: byId("heroImageFileName"),
    heroPreviewImage: byId("heroPreviewImage"),
    storeSlugInput: byId("storeSlug"),
    storeSlugPreview: byId("storeSlugPreview"),
    storeUrlDisplay: byId("storeUrlDisplay"),
    btnCopyStoreLink: byId("btnCopyStoreLink"),
    btnDownloadStoreQr: byId("btnDownloadStoreQr"),
    storeQrWarning: byId("storeQrWarning"),
    storeQrPanel: byId("storeQrPanel"),
    storeQrImage: byId("storeQrImage"),
    storeQrLabel: byId("storeQrLabel"),
    sitePhoneNumberInput: byId("sitePhoneNumber"),
    googleMapsUrlInput: byId("googleMapsUrl"),
    whatsappUrlInput: byId("whatsappUrl"),
    messengerUrlInput: byId("messengerUrl"),
    telegramUrlInput: byId("telegramUrl"),
    facebookUrlInput: byId("facebookUrl"),
    instagramUrlInput: byId("instagramUrl"),
    tiktokUrlInput: byId("tiktokUrl"),
    ordersEnabledInput: byId("ordersEnabled"),
    serviceCountryInput: byId("serviceCountry"),
    serviceRegionInput: byId("serviceRegion"),
    settingsReadiness: byId("settingsReadiness"),
    readinessScore: byId("readinessScore"),
    readinessFill: byId("readinessFill"),
    readinessSteps: byId("readinessSteps"),
    btnSaveSettings: byId("btnSaveSettings"),
    productsTableBody: byId("productsTableBody"),
    categoriesTableBody: byId("categoriesTableBody"),
    ordersTableBody: byId("ordersTableBody"),
    tabs: Array.from(document.querySelectorAll(".tab")),
    summaryNewOrders: byId("summaryNewOrders"),
    summaryTotalOrders: byId("summaryTotalOrders"),
    summarySiteVisits: byId("summarySiteVisits"),
    adminToastStack: byId("adminToastStack"),
    adminConfirmModal: byId("adminConfirmModal"),
    adminConfirmTitle: byId("adminConfirmTitle"),
    adminConfirmMessage: byId("adminConfirmMessage"),
    btnConfirmCancel: byId("btnConfirmCancel"),
    btnConfirmAccept: byId("btnConfirmAccept"),
  };
}

function createText() {
  const fallback = {
    unknownSupabaseError: "حدث خطأ غير متوقع. حاول مرة أخرى.",
    chooseCategory: "اختر التصنيف",
    addCategoryFirst: "أنشئ تصنيفا أولا",
    noCategoriesAvailable: "لا توجد تصنيفات متاحة",
    noProductsYet: "لا توجد منتجات مضافة حتى الآن.",
    noCategoriesYet: "لا توجد تصنيفات مضافة حتى الآن.",
    noOrdersYet: "لا توجد طلبات واردة حتى الآن.",
    available: "متوفر",
    unavailable: "غير متوفر",
    edit: "تعديل",
    delete: "حذف",
    activate: "تفعيل",
    disable: "تعطيل",
    process: "معالجة",
    complete: "إكمال",
    cancelOrder: "إلغاء الطلب",
    none: "لا يوجد",
    loadingSave: "جار الحفظ...",
    dashboardLoadError: "تعذر تحميل البيانات الآن. حاول مرة أخرى.",
    categoryNameRequired: "اسم التصنيف مطلوب.",
    duplicateCategory: "يوجد تصنيف آخر بالاسم نفسه.",
    settingsSaved: "تم حفظ التغييرات بنجاح.",
    productSaved: "تم حفظ المنتج بنجاح.",
    categorySaved: "تم حفظ التصنيف بنجاح.",
    productDeleted: "تم حذف المنتج.",
    categoryDeleted: "تم حذف التصنيف.",
    availabilityEnabled: "تم تفعيل المنتج.",
    availabilityDisabled: "تم تعطيل المنتج.",
    orderUpdated: "تم تحديث حالة الطلب.",
    toastSuccess: "تم بنجاح",
    toastError: "حدث خطأ",
    toastWarning: "تنبيه",
    toastInfo: "معلومة",
    confirmAction: "متابعة",
    confirmTitle: "تأكيد العملية",
    supabaseRequired: "أكمل ربط Supabase أولا لبدء استخدام اللوحة.",
    previewGateBlocked: "أكد بريدك أولا لفتح هذه الميزة.",
    saveProductError: "تعذر حفظ المنتج الآن. حاول مرة أخرى.",
    saveCategoryError: "تعذر حفظ التصنيف الآن. حاول مرة أخرى.",
    saveSettingsError: "تعذر حفظ التغييرات الآن. حاول مرة أخرى.",
    deleteProductError: "تعذر حذف المنتج الآن. حاول مرة أخرى.",
    deleteCategoryError: "تعذر حذف التصنيف الآن. حاول مرة أخرى.",
    cannotDeleteCategory: (name, count) => `لا يمكن حذف التصنيف "${name}" لأنه مستخدم في ${count} منتج.`,
    confirmDeleteCategory: (name) => `هل أنت متأكد من حذف التصنيف "${name}"؟`,
    orderStatusLabel(status) {
      return { processing: "قيد المعالجة", completed: "مكتمل", cancelled: "ملغي" }[status] || "جديد";
    },
  };

  return {
    ...fallback,
    ...ADMIN_RENDER_UI_TEXT,
    ...ADMIN_UI_TEXT,
  };
}

function createValidationText() {
  return {
    productNameRequired: "اسم المنتج مطلوب.",
    productNameInvalid: "اسم المنتج يجب أن يكون بين 2 و120 حرفا.",
    duplicateProduct: "يوجد منتج آخر بالاسم نفسه.",
    productPriceInvalid: "أدخل سعرا صحيحا أكبر من صفر.",
    productCategoryRequired: "اختر التصنيف أولا.",
    categoryNameInvalid: "اسم التصنيف يجب أن يكون بين 2 و80 حرفا.",
    categoryIconInvalid: "يمكن إدخال أيقونة واحدة فقط لكل تصنيف.",
    invalidStoreSlug: "اكتب رابط متجر صحيحا بحروف إنجليزية صغيرة وأرقام وشرطات فقط.",
    duplicateStoreSlug: "هذا الرابط مستخدم بالفعل في متجر آخر.",
    invalidHeroImageUrl: "أدخل رابط صورة صحيحا أو اترك الحقل فارغا.",
    invalidPhoneNumber: "أدخل رقم هاتف صحيحا.",
    invalidWhatsAppNumber: "أدخل رقم واتساب صحيحا.",
    invalidMessengerHandle: "أدخل معرف مسنجر صحيحا.",
    invalidTelegramHandle: "أدخل يوزر تلجرام صحيحا.",
    invalidGoogleMapsUrl: "أدخل رابط جوجل ماب صحيحا.",
    invalidFacebookUrl: "أدخل رابط فيسبوك صحيحا.",
    invalidInstagramUrl: "أدخل رابط إنستغرام صحيحا.",
    invalidTiktokUrl: "أدخل رابط تيك توك صحيحا.",
    serviceCountryInvalid: "اكتب اسم الدولة بشكل صحيح.",
    serviceRegionInvalid: "اكتب اسم الولاية بشكل صحيح.",
    contactUsed: (label) => `${label} مستخدم بالفعل في متجر آخر.`,
    ...ADMIN_VALIDATION_UI_TEXT,
  };
}

export function createAdminContext(dependencies) {
  const DEFAULT_SITE_SETTINGS = { ...dependencies.BASE_SITE_SETTINGS };
  const { runtimeGuard, state, setState } = createStateStore({
    ui: {
      view: "settingsTab",
      loading: false,
      error: null,
      previewMode: false,
      productFormDirty: false,
      categoryFormDirty: false,
      settingsFormDirty: false,
      initialized: false,
      dashboardRefreshTimer: null,
      authSyncPromise: null,
      hasReceivedInitialAuthState: false,
      currentStorefrontUrl: "",
      currentStoreQrDataUrl: "",
      storeQrRenderToken: 0,
    },
    entities: {
      products: [],
      categories: [],
      orders: [],
      siteStats: { total_visits: 0 },
      siteSettings: { ...DEFAULT_SITE_SETTINGS },
    },
    session: {
      user: null,
      tenant: null,
    },
    draft: {
      editingProduct: null,
      editingCategory: null,
      confirmResolver: null,
    },
  }, { label: "admin" });

  const legacyState = {
    get currentSession() { return state.session.user; },
    get currentTenant() { return state.session.tenant; },
    get categories() { return state.entities.categories; },
    get products() { return state.entities.products; },
    get orders() { return state.entities.orders; },
    get siteStats() { return state.entities.siteStats; },
    get siteSettings() { return state.entities.siteSettings; },
    get editingProduct() { return state.draft.editingProduct; },
    get editingCategory() { return state.draft.editingCategory; },
    get confirmResolver() { return state.draft.confirmResolver; },
    get dashboardRefreshTimer() { return state.ui.dashboardRefreshTimer; },
    get isProductFormDirty() { return state.ui.productFormDirty; },
    get isCategoryFormDirty() { return state.ui.categoryFormDirty; },
    get isSettingsFormDirty() { return state.ui.settingsFormDirty; },
    get isAdminUiInitialized() { return state.ui.initialized; },
    get isPreviewMode() { return state.ui.previewMode; },
    get authSyncPromise() { return state.ui.authSyncPromise || Promise.resolve(); },
    get hasReceivedInitialAuthState() { return state.ui.hasReceivedInitialAuthState; },
    get currentStorefrontUrl() { return state.ui.currentStorefrontUrl; },
    get currentStoreQrDataUrl() { return state.ui.currentStoreQrDataUrl; },
    get storeQrRenderToken() { return state.ui.storeQrRenderToken; },
  };

  return {
    dependencies,
    elements: getElements(),
    appState: state,
    state: legacyState,
    setState,
    runtimeGuard,
    TEXT: createText(),
    VALIDATION_TEXT: createValidationText(),
    ADMIN_FIELD_LABELS_UI,
    ADMIN_RENDER_UI_TEXT,
    DEFAULT_CATEGORY_ICON: "\u{1F37D}\uFE0F",
    DEFAULT_SITE_SETTINGS,
    UNVERIFIED_SESSION_KEY: "ordely-unverified",
    renderIcon,
    validation: {},
    render: {},
    actions: {},
  };
}
