export const UI_TEXT_AR = {
  common: {
    success: "تم",
    error: "تعذر التنفيذ، أعد المحاولة",
    warning: "انتبه",
    info: "تم التحديث",
    cancel: "إلغاء",
    confirm: "متابعة",
    fileNotSelected: "لم يتم اختيار ملف",
  },

  auth: {
    guidance: {
      signup: {
        eyebrow: "إنشاء حساب",
        title: "أنشئ حسابك وابدأ البيع",
        text: "أنشئ الحساب ثم أكد بريدك",
        points: [
          ["بريد صحيح", "يُستخدم للدخول واسترجاع الحساب"],
          ["كلمة مرور قوية", "ثمانية أحرف على الأقل"],
          ["مسار واضح", "بعد التأكيد نوجهك للخطوة المناسبة"],
        ],
      },
      access: {
        eyebrow: "الوصول للحساب",
        title: "افتح حسابك وتابع الإدارة",
        text: "أدخل بيانات حسابك ثم نوجهك للوحة المناسبة",
        points: [
          ["حساب موجود", "استخدم نفس البريد الذي أنشأت به المتجر"],
          ["دخول مباشر", "بعد التحقق نعيدك إلى مركز التوجيه"],
          ["قرار مركزي", "Entry يحدد هل تفتح اللوحة أو الإعداد"],
        ],
      },
    },

    copy: {
      backHome: "العودة",
      emailLabel: "البريد الإلكتروني",
      passwordLabel: "كلمة المرور",
      passwordPlaceholder: "8 أحرف على الأقل",
      signupTitle: "إنشاء حساب",
      signupSubtitle: "أنشئ الحساب وابدأ استقبال الطلبات",
      signupSubmit: "إنشاء الحساب",
      signingUp: "جارٍ إنشاء الحساب",
      accessTitle: "الوصول إلى حسابك",
      accessSubtitle: "أدخل بريدك وكلمة المرور لفتح لوحتك",
      accessSubmit: "فتح الحساب",
      signingIn: "جارٍ فتح الحساب",
      switchToAccessPrompt: "لديك حساب بالفعل؟",
      switchToAccessAction: "تسجيل الدخول",
      switchToSignupPrompt: "ليس لديك حساب بعد؟",
      switchToSignupAction: "إنشاء حساب",
      checkingAccount: "جارٍ التحقق",
      accountTitle: "ابدأ حسابك",
      accountSubtitle: "أدخل بريدك وكلمة المرور للبدء.",
      accountSignupTitle: "إنشاء حساب",
      accountSubmit: "متابعة",
      accountSignupSubmit: "إنشاء حساب",
      confirmTitle: "تم إنشاء حسابك",
      confirmVerifyTitle: "أكد بريدك",
      confirmSubtitle: "تابع الآن إعداد المتجر.",
      confirmEmailSubtitle: "افتح بريدك واضغط رابط التأكيد، ثم تابع إعداد المتجر.",
      confirmContinue: "متابعة إعداد المتجر",
      signupSuccessTitle: "تم إنشاء حسابك",
      signupSuccessEmailSent: "أرسلنا رابط التأكيد إلى بريدك",
      signupSuccessContinue: "يمكنك الدخول الآن",
      signupSuccessVerifyHint: "لتفعيل استقبال الطلبات، أكد بريدك",
      setupTitle: "أكمل المتجر",
      setupSubtitle: "حدد رابط المتجر ووسيلة التواصل الأساسية.",
      storeSlugLabel: "رابط المتجر",
      storeSlugPlaceholder: "my-store",
      contactLabel: "واتساب أو هاتف",
      contactPlaceholder: "0550000000",
      setupSubmit: "فتح لوحة التحكم",
      openingDashboard: "جارٍ فتح لوحة التحكم",
    },

    validation: {
      passwordTooShort: "كلمة المرور قصيرة",
      passwordTooLong: "كلمة المرور طويلة",
      passwordNeedsLettersAndNumbers: "استخدم أحرفًا وأرقامًا",
      accountFieldsRequired: "أكمل بيانات الحساب",
      emailInvalid: "بريد غير صحيح",
      passwordMismatch: "كلمة المرور غير متطابقة",
      storeSlugInvalid: "رابط غير صحيح",
      contactInvalid: "رقم غير صحيح",
      setupFieldsRequired: "أكمل بيانات المتجر",
    },

    feedback: {
      emailConfirmationRequired: "قم بتأكيد بريدك ثم أعد المحاولة",
      emailAlreadyUsed: "البريد مستخدم",
      accountAlreadyExists: "الحساب موجود مسبقًا",
      invalidCredentials: "بيانات الدخول غير صحيحة",
      accessFailed: "تعذر فتح الحساب",
      genericError: "تعذر التنفيذ",
      openingAdmin: "جارٍ فتح لوحة التحكم",
      signupCreated: "تم إنشاء الحساب، تحقق من بريدك",
      authUnavailable: "الخدمة غير متاحة الآن",
      sessionCheckFailed: "تعذر التحقق من الجلسة",
    },

    entry: {
      loadingTitle: "جارٍ التحقق",
      loadingText: "لحظة واحدة...",
      confirmTitle: "أكد بريدك الإلكتروني",
      confirmHint: "بعد الضغط على الرابط، ارجع هنا وانقر تابع.",
      confirmAction: "أكدت البريد - تابع",
      backToAuth: "العودة للتسجيل",
      errorTitle: "تعذر المتابعة",
      accountReadError: "تعذر قراءة الحساب. حاول مرة أخرى.",
      confirmationPending: "لم يتم التأكيد بعد. تحقق من بريدك وأعد المحاولة.",
      confirmationLinkPending: "لم يتم التأكيد بعد. افتح الرابط في بريدك أولًا.",
      serviceUnavailable: "الخدمة غير متاحة الآن",
      bootFailed: "تعذر التشغيل. ارجع وحاول مرة أخرى.",
      emailFallback: "بريدك",
      confirmSent(email) { return `أرسلنا رابط التأكيد إلى ${email || this.emailFallback}`; },
    },

    onboarding: {
      contactHintWhatsapp: "سيُستخدم كقناة واتساب أساسية",
      contactHintPhone: "سيُستخدم كرقم هاتف للتواصل",
      points: [["رابط واضح", "رابط مباشر يصل إليه العميل بنقرة واحدة."], ["قناة تواصل", "واتساب أو هاتف لاستقبال الطلبات والرد."], ["لوحة جاهزة", "بعد الحفظ تنتقل مباشرة لإدارة المنتجات."]],
      saving: "جارٍ إعداد المتجر...",
      saveFailed: "تعذر إعداد المتجر الآن. حاول مرة أخرى.",
      serviceUnavailable: "الخدمة غير متاحة الآن",
      bootFailed: "تعذر تشغيل صفحة الإعداد",
    },
  },

  store: {
    socialPlatforms: [
      { key: "facebook_url", label: "فيسبوك", className: "facebook", icon: "facebook" },
      { key: "instagram_url", label: "إنستغرام", className: "instagram", icon: "instagram" },
      { key: "tiktok_url", label: "تيك توك", className: "tiktok", icon: "tiktok" },
    ],

    actionPlatforms: [
      { key: "google_maps_url", label: "الموقع", className: "btn-map", icon: "map" },
      { key: "whatsapp_url", label: "واتساب", className: "btn-whatsapp", icon: "whatsapp" },
      { key: "messenger_url", label: "مسنجر", className: "btn-messenger", icon: "messenger" },
      { key: "telegram_url", label: "تلجرام", className: "btn-telegram", icon: "telegram" },
      { key: "phone_number", label: "اتصال", className: "btn-call", icon: "phone" },
    ],

    orderChannelLabels: {
      whatsapp_url: "واتساب",
      phone_number: "اتصال",
      messenger_url: "مسنجر",
      telegram_url: "تلجرام",
    },

    toastTitle(type = "success") {
      return type === "error" ? "تعذر التنفيذ" : "تم الطلب";
    },

    serviceArea(location) {
      return `الخدمة داخل ${location}`;
    },

    orderButton(channelLabel) {
      return channelLabel ? `اطلب عبر ${channelLabel}` : "اطلب الآن";
    },

    orderSubmitLabel(channelLabel) {
      return channelLabel ? `تأكيد الطلب عبر ${channelLabel}` : "تأكيد الطلب";
    },

    price(value) {
      return `${value} د.ج`;
    },

    allCategory: "الكل",
    noImage: "بدون صورة",
    noProductsInCategory: "لا توجد منتجات في هذا التصنيف",
    noProductsAvailable: "لا توجد منتجات حالياً",
    storeNotFound: "المتجر غير متوفر",
    invalidCustomerName: "اسم غير صالح",
    invalidCustomerPhone: "رقم غير صالح",
    invalidQuantity: "كمية غير صحيحة",
    orderCreateError: "تعذر إرسال الطلب",
    completeInfoBeforeConfirm: "أكمل البيانات",
    invalidNameBeforeConfirm: "اسم غير صالح",
    invalidPhoneBeforeConfirm: "رقم غير صالح",
    quantityRange: "الكمية بين 1 و99",
    sendingOrder: "جارٍ إرسال الطلب",
    orderRegisteredWithChannel: "تم فتح القناة برسالة جاهزة",

    orderSent(productName) {
      return `تم إرسال طلب ${productName}`;
    },
  },

  admin: {
    copy: {
      unknownSupabaseError: "تعذر التنفيذ",
      chooseCategory: "اختر التصنيف",
      addCategoryFirst: "أنشئ تصنيفًا أولًا",
      noCategoriesAvailable: "لا توجد تصنيفات",
      noProductsYet: "لا توجد منتجات",
      noCategoriesYet: "لا توجد تصنيفات",
      noOrdersYet: "لا توجد طلبات",
      available: "متوفر",
      unavailable: "غير متوفر",
      edit: "تعديل",
      delete: "حذف",
      activate: "تفعيل",
      disable: "تعطيل",
      process: "قيد المعالجة",
      complete: "مكتمل",
      cancelOrder: "إلغاء الطلب",
      none: "لا يوجد",
      addProduct: "أضف منتجًا",
      createProduct: "إنشاء منتج",
      saveChanges: "حفظ التغييرات",
      addProductTitle: "إنشاء منتج",
      editProductTitle: "تعديل المنتج",
      addProductSubtitle: "أدخل البيانات",
      editProductSubtitle: "عدّل البيانات",
      addCategory: "إنشاء تصنيف",
      createCategory: "إنشاء تصنيف",
      addCategoryTitle: "إنشاء تصنيف",
      editCategoryTitle: "تعديل التصنيف",
      addCategorySubtitle: "أدخل الاسم",
      editCategorySubtitle: "عدّل الاسم",
      saveCategory: "حفظ التصنيف",
      saveSettings: "حفظ الإعدادات",
      loadingSave: "جارٍ الحفظ",
      dashboardLoadError: "تعذر تحميل البيانات",
      loginFailed: "تعذر الدخول",
      confirmDeleteProduct: "حذف المنتج؟",
      deleteProductError: "تعذر حذف المنتج",
      deleteCategoryError: "تعذر حذف التصنيف",
      saveProductError: "تعذر حفظ المنتج",
      saveCategoryError: "تعذر حفظ التصنيف",
      saveSettingsError: "تعذر حفظ الإعدادات",
      categoryNameRequired: "اسم التصنيف مطلوب",
      categoryIconRequired: "أيقونة التصنيف مطلوبة",
      duplicateCategory: "التصنيف موجود",
      settingsSaved: "تم حفظ الإعدادات",
      productSaved: "تم حفظ المنتج",
      categorySaved: "تم حفظ التصنيف",
      productDeleted: "تم حذف المنتج",
      categoryDeleted: "تم حذف التصنيف",
      availabilityEnabled: "تم التفعيل",
      availabilityDisabled: "تم التعطيل",
      orderUpdated: "تم تحديث الطلب",
      toastSuccess: "تم",
      toastError: "خطأ",
      toastWarning: "تنبيه",
      toastInfo: "تم",
      cancel: "إلغاء",
      confirmAction: "متابعة",
      confirmTitle: "تأكيد",
      fileNotSelected: "لم يتم اختيار ملف",
      supabaseRequired: "أكمل الإعدادات",

      cannotDeleteCategory(categoryName, usageCount) {
        return `لا يمكن حذف "${categoryName}" (مستخدم في ${usageCount})`;
      },

      confirmDeleteCategory(categoryName) {
        return `حذف "${categoryName}"؟`;
      },

      orderStatusLabel(status) {
        if (status === "processing") return "قيد المعالجة";
        if (status === "completed") return "مكتمل";
        if (status === "cancelled") return "ملغي";
        return "جديد";
      },

      storeQrLabel: "امسح لفتح المتجر",
      storeQrGenerateError: "تعذر إنشاء QR",
      storeLinkRequired: "حدد رابط المتجر",
      storeLinkCopied: "تم نسخ الرابط",
      storeLinkCopyError: "تعذر النسخ",
      storeQrDownloaded: "تم تحميل QR",
      openingAdmin: "جارٍ فتح الإدارة",
      checkingSession: "جارٍ التحقق",
      sessionMissingRedirect: "لا توجد جلسة، سيتم تحويلك",
      adminRequiresConfirmedEmail: "أكد بريدك أولًا",
      adminOpenAccountError: "تعذر فتح الإدارة",
      adminRequiresConnection: "أكمل الإعدادات",
      checkingAccountThenAdmin: "جارٍ التحقق ثم الدخول",
      sessionDelayed: "تأخر التحقق",
      retryOrReturnToLogin: "أعد المحاولة أو ارجع للدخول",
      deleteProductTitle: "حذف المنتج",
      deleteCategoryTitle: "حذف التصنيف",
      cancelOrderTitle: "إلغاء الطلب",
      cancelOrderMessage: "إلغاء هذا الطلب؟",
      accountVerifiedButAdminSetupFailed: "تم التحقق لكن فشل الدخول",
      adminPageBootError: "تعذر تشغيل الصفحة",
    },

    validation: {
      authEmailNotConfirmed: "أكد بريدك",
      productNameRequired: "اسم المنتج مطلوب",
      productNameInvalid: "اسم غير صالح",
      duplicateProduct: "المنتج موجود",
      productPriceInvalid: "سعر غير صحيح",
      productCategoryRequired: "اختر التصنيف",
      categoryNameInvalid: "اسم غير صالح",
      categoryIconRequired: "أيقونة التصنيف مطلوبة",
      categoryIconInvalid: "أيقونة غير صحيحة",
      invalidStoreSlug: "رابط غير صالح",
      duplicateStoreSlug: "الرابط مستخدم",
      invalidHeroImageUrl: "رابط غير صحيح",
      invalidPhoneNumber: "رقم غير صحيح",
      invalidWhatsAppNumber: "رقم غير صحيح",
      invalidMessengerHandle: "معرف غير صحيح",
      invalidTelegramHandle: "يوزر غير صحيح",
      invalidGoogleMapsUrl: "رابط غير صحيح",
      invalidFacebookUrl: "رابط غير صحيح",
      invalidInstagramUrl: "رابط غير صحيح",
      invalidTiktokUrl: "رابط غير صحيح",
      serviceCountryInvalid: "الدولة غير صحيحة",
      serviceRegionInvalid: "المنطقة غير صحيحة",

      contactUsed(label) {
        return `${label} مستخدم`;
      },
    },

    fieldLabels: {
      phone: "رقم الهاتف",
      whatsapp: "واتساب",
      messenger: "مسنجر",
      telegram: "تلجرام",
      googleMaps: "جوجل ماب",
      facebook: "فيسبوك",
      instagram: "إنستغرام",
      tiktok: "تيك توك",
    },

    render: {
      noImage: "بدون صورة",
      icon: "الرمز",
      image: "الصورة",
      name: "الاسم",
      price: "السعر",
      category: "التصنيف",
      clicks: "النقرات",
      status: "الحالة",
      actions: "إجراءات",
      productCount: "عدد المنتجات",
      displayOrder: "ترتيب",
      product: "المنتج",
      customer: "العميل",
      phone: "الهاتف",
      quantity: "الكمية",
      date: "التاريخ",
    },
  },

  channelEngine: {
    defaultTemplateLines: [
      "مرحبًا، أريد طلب:",
      "",
      "المنتج: {product_name}",
      "السعر: {product_price}",
      "",
      "رابط المنتج:",
      "{product_url}",
      "",
      "هل هو متوفر؟",
      "أريد تأكيد الطلب.",
    ],
  },
};

export const COMMON_UI_TEXT = UI_TEXT_AR.common;
export const AUTH_UI_TEXT = UI_TEXT_AR.auth;
export const STORE_UI_TEXT = UI_TEXT_AR.store;
export const ADMIN_UI_TEXT = UI_TEXT_AR.admin.copy;
export const ADMIN_VALIDATION_UI_TEXT = UI_TEXT_AR.admin.validation;
export const ADMIN_FIELD_LABELS_UI = UI_TEXT_AR.admin.fieldLabels;
export const ADMIN_RENDER_UI_TEXT = UI_TEXT_AR.admin.render;
export const CHANNEL_ENGINE_UI_TEXT = UI_TEXT_AR.channelEngine;

export const HTML_PAGE_UI_TEXT_AR = {
  landing: {
    documentTitle: "Ordely | حوّل متابعينك إلى طلبات فعلية",
    heroHeadline: "طلباتك تضيع وسط الأسئلة المتكررة؟",
    heroText: "اعرض منتجاتك برابط واحد، واجعل العميل يطلب مباشرة بدون رسائل طويلة.",
    platformStripText: "استقبل الطلبات عبر القنوات التي يستخدمها عملاؤك",
    primaryAction: "ابدأ الآن",
    loginAction: "تسجيل الدخول",
    secondaryAction: "شاهد مثال",
    quickBenefitsAria: "فوائد سريعة",
    quickBenefitFastOrder: "طلب أسرع",
    quickBenefitLessExplaining: "شرح أقل",
    quickBenefitClearerDisplay: "عرض أوضح",
    previewAria: "معاينة تجربة الطلب",
    previewTitle: "من مشاهدة المنتج إلى الطلب",
    previewText: "مسار واضح يقلل التردد ويزيد فرص البيع.",
    previewPillProduct: "منتج واضح",
    previewPillOrder: "زر طلب مباشر",
    previewMetricLess: "أقل",
    previewMetricLessLabel: "أسئلة متكررة",
    previewMetricFaster: "أسرع",
    previewMetricFasterLabel: "قرار الشراء",
    previewMetricClearer: "أوضح",
    previewMetricClearerLabel: "للعميل",
    trustStores: "+100 متجر يستخدم Ordely",
    trustQuestions: "تقليل الأسئلة حتى 70%",
    trustOrders: "طلبات أسرع خلال ثوانٍ",
    problemTitle: "أين تضيع الطلبات؟",
    problemText: "المشكلة غالبًا في طريقة العرض، لا في المنتج.",
    problemLostTitle: "العميل يتوه",
    problemLostText: "الصور والأسعار والردود موزعة في أكثر من مكان.",
    problemQuestionsTitle: "تتكرر الأسئلة",
    problemQuestionsText: "تشرح السعر والتوفر وطريقة الطلب كل مرة.",
    problemDelayTitle: "الطلب يتأخر",
    problemDelayText: "كل خطوة إضافية تقلل احتمال إتمام الطلب.",
    solutionTitle: "اجعل طريق الطلب واضحًا",
    solutionText: "صفحة واحدة تجمع المنتجات وتدفع العميل للخطوة التالية فورًا.",
    solutionProducts: "منتجات واضحة",
    solutionOrder: "طلب مباشر",
    howTitle: "ابدأ في 3 خطوات",
    howStepOne: "أنشئ حسابك",
    howStepTwo: "أضف منتجاتك",
    howStepThree: "استقبل الطلبات",
    demoKicker: "مثال مباشر",
    demoTitle: "شاهد النتيجة قبل أن تبدأ",
    demoText: "افتح متجرًا جاهزًا وشاهد كيف يتحرك العميل نحو الطلب.",
    demoOpenStore: "افتح المتجر",
    valueTimeTitle: "وقت أقل في الرد",
    valueTimeText: "كل إجابة مهمة تظهر قبل أن يسأل العميل.",
    valueDecisionTitle: "قرار شراء أسرع",
    valueDecisionText: "العميل يرى المنتج والخطوة التالية فورًا.",
    valueTrustTitle: "ثقة أعلى",
    valueTrustText: "عرض مرتب يجعل متجرك يبدو جاهزًا للطلب.",
    ctaTitle: "ابدأ الآن أو استمر في خسارة الطلبات",
    ctaText: "حوّل المتابع المهتم إلى عميل يعرف ماذا يطلب وكيف يطلب.",
  },

  authPage: {
    documentTitle: "Ordely | ابدأ البيع الآن",
    pageAria: "الدخول إلى Ordely",
    sideEyebrow: "ابدأ البيع بوضوح",
    sideTitle: "حوّل المتابع المهتم إلى طلب واضح",
    sideText: "أنشئ حسابك، أضف منتجاتك، واجعل العميل يعرف ماذا يطلب وكيف يطلب.",
    title: UI_TEXT_AR.auth.copy.accountTitle,
    subtitle: UI_TEXT_AR.auth.copy.accountSubtitle,
    emailLabel: "البريد الإلكتروني",
    passwordLabel: "كلمة المرور",
    passwordPlaceholder: "8 أحرف على الأقل",
    accountSubmit: UI_TEXT_AR.auth.copy.accountSubmit,
    confirmTitle: UI_TEXT_AR.auth.copy.confirmTitle,
    confirmSubtitle: UI_TEXT_AR.auth.copy.confirmSubtitle,
    confirmContinue: UI_TEXT_AR.auth.copy.confirmContinue,
    setupTitle: UI_TEXT_AR.auth.copy.setupTitle,
    setupSubtitle: UI_TEXT_AR.auth.copy.setupSubtitle,
    storeSlugLabel: UI_TEXT_AR.auth.copy.storeSlugLabel,
    storeSlugPlaceholder: UI_TEXT_AR.auth.copy.storeSlugPlaceholder,
    contactLabel: UI_TEXT_AR.auth.copy.contactLabel,
    contactPlaceholder: UI_TEXT_AR.auth.copy.contactPlaceholder,
    setupSubmit: UI_TEXT_AR.auth.copy.setupSubmit,
  },

  entryPage: { documentTitle: "Ordely | توجيه الحساب", pageAria: "توجيه الحساب", sideEyebrow: "ابدأ البيع بوضوح", sideTitle: "جارٍ تهيئة حسابك", sideText: "سيتم توجيهك تلقائيًا إلى الخطوة المناسبة." },

  onboardingPage: { documentTitle: "Ordely | إعداد المتجر", pageAria: "إعداد متجر Ordely", sideEyebrow: "ابدأ البيع بوضوح", sideTitle: "خطوتان وتفتح المتجر", sideText: "رابط واضح وقناة تواصل - هذا كل ما تحتاجه للبدء.", title: "أكمل إعداد المتجر", subtitle: "رابط متجرك + قناة التواصل = جاهز لاستقبال الطلبات", storeSlugLabel: UI_TEXT_AR.auth.copy.storeSlugLabel, storeSlugPlaceholder: UI_TEXT_AR.auth.copy.storeSlugPlaceholder, slugPreviewLabel: "معاينة الرابط:", contactLabel: UI_TEXT_AR.auth.copy.contactLabel, contactPlaceholder: UI_TEXT_AR.auth.copy.contactPlaceholder, submit: UI_TEXT_AR.auth.copy.setupSubmit },

  storePage: {
    documentTitle: "Ordely Store",
    socialLinksAria: "روابط التواصل",
    serviceAreaTitle: "نطاق الخدمة",
    serviceAreaText: "الخدمة متاحة داخل نطاق محدد فقط.",
    categoriesAria: "التصنيفات",
    loading: "جارٍ التحميل...",
    orderModalTitle: "أكمل طلبك",
    orderModalText: "أدخل معلوماتك الأساسية ليصلك الرد بسرعة.",
    orderModalCloseAria: "إغلاق",
    orderStep1Label: "المنتج",
    orderStep2Label: "بياناتك",
    orderProductName: "اسم المنتج",
    orderProductMeta: "0 د.ج",
    orderMessageTitle: "الرسالة الجاهزة",
    orderCustomerNameLabel: "الاسم",
    orderCustomerNamePlaceholder: "محمد علي",
    orderCustomerPhoneLabel: "رقم الهاتف",
    orderQuantityLabel: "الكمية",
    orderSubmit: "تأكيد الطلب",
  },

  adminPage: {
    documentTitle: "لوحة التحكم",
    headerTitle: "لوحة التحكم",
    openStoreAria: "فتح المتجر",
    newOrdersAria: "الطلبات الجديدة",
    logoutAria: "تسجيل الخروج",
    logout: "تسجيل الخروج",
    authSectionTitle: "التحقق من الدخول",
    authSectionNote:
      "هذه الصفحة مخصصة فقط للتحقق من الجلسة قبل فتح الإدارة. إذا لم يتم التحويل تلقائيًا ستظهر لك الخطوة المناسبة هنا.",
    authGateMessage: ADMIN_UI_TEXT.checkingAccountThenAdmin,
    goToLogin: "الذهاب إلى تسجيل الدخول",
    retry: "إعادة المحاولة",
    authLogout: "تسجيل الخروج",
    tabProducts: "المنتجات",
    tabCategories: "التصنيفات",
    tabOrders: "الطلبات",
    tabSettings: "إعدادات المتجر",
    productsToolbarTitle: "قائمة المنتجات",
    productsToolbarText: "كل منتج تحفظه هنا يظهر مباشرة للعميل داخل المتجر.",
    createProduct: ADMIN_UI_TEXT.createProduct,
    tableImage: ADMIN_RENDER_UI_TEXT.image,
    tableName: ADMIN_RENDER_UI_TEXT.name,
    tablePrice: ADMIN_RENDER_UI_TEXT.price,
    tableCategory: ADMIN_RENDER_UI_TEXT.category,
    tableClicks: ADMIN_RENDER_UI_TEXT.clicks,
    tableStatus: ADMIN_RENDER_UI_TEXT.status,
    tableActions: ADMIN_RENDER_UI_TEXT.actions,
    productEditorTitle: ADMIN_UI_TEXT.addProductTitle,
    productEditorSubtitle: "هذا المنتج سيظهر مباشرة للعملاء بعد حفظه.",
    close: "إغلاق",
    productNameLabel: "اسم المنتج",
    productNamePlaceholder: "برغر دجاج",
    productPriceLabel: "السعر",
    productCategoryLabel: "التصنيف",
    productCategoryHint: ADMIN_UI_TEXT.addCategoryFirst,
    productImageLabel: "صورة المنتج",
    pickImage: "اختيار صورة",
    fileNotSelected: ADMIN_UI_TEXT.fileNotSelected,
    currentImagePrefix: "الحالية:",
    addProduct: "إضافة منتج",
    cancel: COMMON_UI_TEXT.cancel,
    categoriesToolbarTitle: "قائمة التصنيفات",
    categoriesToolbarText: "نظّم المنتجات في أقسام واضحة حتى يصل العميل لما يريده أسرع.",
    createCategory: "إنشاء تصنيف",
    categoryEditorTitle: "إنشاء تصنيف جديد",
    categoryEditorSubtitle: "هذا التصنيف يساعد العميل على التنقل بسرعة بين المنتجات.",
    categoryNameLabel: "اسم التصنيف",
    categoryNamePlaceholder: "برغر",
    categoryOrderLabel: "ترتيب الظهور",
    categoryIconLabel: "رمز التصنيف",
    addCategory: "إضافة تصنيف",
    ordersToolbarTitle: "قائمة الطلبات",
    ordersToolbarText: "تظهر هنا الطلبات المباشرة القادمة من الواجهة مع حالة كل طلب.",
    summaryNewOrders: "طلبات جديدة",
    summaryTotalOrders: "إجمالي الطلبات",
    summarySiteVisits: "زيارات الموقع",
    orderTableProduct: ADMIN_RENDER_UI_TEXT.product,
    orderTableCustomer: ADMIN_RENDER_UI_TEXT.customer,
    orderTablePhone: ADMIN_RENDER_UI_TEXT.phone,
    orderTableQuantity: ADMIN_RENDER_UI_TEXT.quantity,
    orderTableStatus: ADMIN_RENDER_UI_TEXT.status,
    orderTableDate: ADMIN_RENDER_UI_TEXT.date,
    orderTableActions: ADMIN_RENDER_UI_TEXT.actions,
    readinessTitle: "ابدأ من إعدادات المتجر",
    readinessText: "أكمل الرابط، الصورة، التواصل، والمنصات قبل فتح المتجر للعملاء.",
    sectionStoreIdentity: "هوية المتجر",
    sectionStoreIdentityLabel: "ما يراه العميل أولًا",
    storeLinkTitle: "رابط المتجر",
    storeSlugLabel: "المعرف",
    storePreviewPrefix: "المعاينة:",
    copyLink: "نسخ الرابط",
    downloadQr: "تحميل QR",
    storeQrWarning: ADMIN_UI_TEXT.storeLinkRequired,
    storeQrLabel: ADMIN_UI_TEXT.storeQrLabel,
    storeQrAlt: "QR Code لرابط المتجر",
    heroTitle: "الصورة الرئيسية",
    heroImageAlt: "معاينة الصورة الرئيسية",
    heroUrlLabel: "رابط الصورة",
    heroHint: "المقاس المستحسن: 1900px × 300px",
    heroUploadLabel: "أو اختر صورة من جهازك",
    ordersOpsTitle: "الطلبات والتشغيل",
    ordersOpsLabel: "طريقة استقبال الطلبات والمناطق التي تعمل عليها",
    ordersEnabledTitle: "استقبال الطلبات",
    ordersEnabledLabel: "استقبال الطلبات مباشرة من المتجر",
    serviceAreaTitle: "نطاق الخدمة",
    serviceCountryLabel: "الدولة",
    serviceCountryPlaceholder: "الجزائر",
    serviceRegionLabel: "الولاية",
    serviceRegionPlaceholder: "سوق أهراس",
    channelsTitle: "الوسائل والتواصل",
    channelsLabel: "الوسائل التي يعتمد عليها العميل للوصول إليك",
    contactButtonsTitle: "أزرار التواصل",
    sitePhoneLabel: "رقم الهاتف",
    whatsappLabel: "رقم واتساب",
    messengerLabel: "معرف مسنجر",
    telegramLabel: "يوزر تلجرام",
    googleMapsLabel: "رابط جوجل ماب",
    socialTitle: "السوشيال ميديا",
    socialLabel: "تظهر أسفل المتجر",
    accountsTitle: "الحسابات",
    facebookLabel: "فيسبوك",
    instagramLabel: "إنستغرام",
    tiktokLabel: "تيك توك",
    saveSettings: ADMIN_UI_TEXT.saveSettings,
    confirmTitle: ADMIN_UI_TEXT.confirmTitle,
    confirmMessage: "هل تريد المتابعة؟",
    confirmCancel: COMMON_UI_TEXT.cancel,
    confirmAccept: COMMON_UI_TEXT.confirm,
  },
};
