export const DEMO_STOREFRONT_CONTEXT = {
  tenant: {
    id: 'demo-tenant',
    slug: 'demo',
  },
  siteSettings: {
    hero_image_url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1900&q=80',
    phone_number: '+213550000000',
    google_maps_url: 'https://maps.google.com/?q=Souk+Ahras+Algeria',
    whatsapp_url: '+213550000000',
    messenger_url: 'ordely.demo',
    telegram_url: '@ordely_demo',
    facebook_url: 'https://facebook.com/ordely.demo',
    instagram_url: 'https://instagram.com/ordely.demo',
    tiktok_url: 'https://tiktok.com/@ordely.demo',
    orders_enabled: true,
    service_country: 'Algeria',
    service_region: 'Souk Ahras',
  },
  categories: [
    { id: 'demo-cat-1', name: 'Sweets', icon: '🧁', order_index: 1 },
    { id: 'demo-cat-2', name: 'Meals', icon: '🍝', order_index: 2 },
    { id: 'demo-cat-3', name: 'Drinks', icon: '🥤', order_index: 3 },
  ],
  products: [
    {
      id: 'demo-product-1',
      name: 'Brownies Box',
      price: 1800,
      category: 'Sweets',
      is_available: true,
      image_url: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=900&q=80',
      click_count: 0,
    },
    {
      id: 'demo-product-2',
      name: 'Mini Cheesecake',
      price: 950,
      category: 'Sweets',
      is_available: true,
      image_url: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=900&q=80',
      click_count: 0,
    },
    {
      id: 'demo-product-3',
      name: 'Creamy Pasta',
      price: 1400,
      category: 'Meals',
      is_available: true,
      image_url: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?auto=format&fit=crop&w=900&q=80',
      click_count: 0,
    },
    {
      id: 'demo-product-4',
      name: 'Fresh Juice',
      price: 450,
      category: 'Drinks',
      is_available: true,
      image_url: 'https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?auto=format&fit=crop&w=900&q=80',
      click_count: 0,
    },
  ],
};
